### ISSUE TITLE
Issue when loading the v5.2.9 driver.

### ISSUE THREAD

**Issue by lion24** [lion24/RTL8812au#7]
Multiple stack traces are printed when the driver is load and perform scanning..

Full dmesg dump attached.

[8812au_bt.log](https://github.com/lion24/RTL8812au/files/1607105/8812au_bt.log)

**Comment by lion24** [comment]
Fix by commit: b5229342083d68434ba136887c5768d1b67c8506

**Comment by D3m0nicw0lf** [comment]
modprobe: ERROR: could not insert '8812au': Unknown symbol in module, or unknown parameter (see dmesg)
 what to do? now i have install each and evry thing 
and latest kali 2018.1

**Comment by lion24** [comment]
Hello, yeah I've the same issue. Since refactoring part of the code it seems some symbol are now missing :( 

Will have a look when I'll have a bit of time.. 

Thanks for your message ;)
